<a href="https://colab.research.google.com/github/Anjalee01/Python-For-Mathematicians/blob/main/Pandas(Python_for_Mathematicians).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Pandas?
Pandas is a powerful and widely-used open-source data manipulation and analysis library in Python. It provides data structures and functions needed to efficiently handle and analyze large datasets. Pandas is particularly well-suited for working with structured data (i.e., data that can be organized into tables, like databases or spreadsheets).

It provides two primary data structures:

**Series:** A one-dimensional labeled array, similar to a list or a column in a table.
                                                                   
**DataFrame:** A two-dimensional table of labeled data, similar to a spreadsheet or SQL table, consisting of rows and columns.

# **Why Pandas?**
Pandas is the go-to library for data manipulation and analysis in Python due to its powerful features, ease of use, and extensive support for various data types and operations. Whether youâ€™re cleaning, transforming, or analyzing data, Pandas makes it all much easier.

![image.png]()

**Each column in a DataFrame is a Series**

---


![image.png]()

# **Creating a Series**

In [ ]:
#import
import pandas as pd

In [ ]:
#Series will convert list into a column which is called series
a=[1,2,3,4]
series1=pd.Series(a)
print(series1)
print(type(series1))

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
#Check label
print(series1[2])

3

In [ ]:
#adding label
label=["row_1","row_2","row_1","row_2"]
df=pd.Series(a, index=label)
print(df["row_1"])
print(df)

row_1    1
row_1    3
dtype: int64
row_1    1
row_2    2
row_1    3
row_2    4
dtype: int64

In [ ]:
#create series froma dictionary
mydic={"country":"pak","fruit":"aplle", "veg":"potato"}
df1=pd.Series(mydic)
print(df1)

country       pak
fruit       aplle
veg        potato
dtype: object

In [ ]:
calories = {"day1": [420,12,30], 14: [380,456,12], "day3": [390,34,56,7]}
myvar=pd.Series(calories)
myvar

day1       [420, 12, 30]
14        [380, 456, 12]
day3    [390, 34, 56, 7]
dtype: object

In [ ]:
myvar.index=["day6","day7","day8"]
print(myvar)

day6       [420, 12, 30]
day7      [380, 456, 12]
day8    [390, 34, 56, 7]
dtype: object

**A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows, and columns.**


---


![image.png]()

# **Creating a Pandas DataFrame**
Pandas DataFrame can be created from the lists, dictionary, and from a list of dictionary etc.

In [ ]:
import numpy as np
#Creating a dataframe using List
list1=["fruits", "country", "furniture", "vegetables"]
# df2=pd.DataFrame(list1)
# df2
df2=pd.DataFrame(np.transpose(list1))
print(df2)

            0
0      fruits
1     country
2   furniture
3  vegetables

In [ ]:
dataframe2=pd.Series(list1)
dataframe2
# print(type(dataframe2))

0        fruits
1       country
2     furniture
3    vegetables
dtype: object

In [ ]:
#Creating a dataframe using dictionary
Country=["PAk","IND","USA","UAE","PARAS","EUROPE","FRANCE","RUSSIA","SAUDIA"]
Population=[12,34,25,45,67,89,90,12,34]
BRate=[345,567,234,678,890,2345,567,896,5678]
mydict={"Country":Country,"Population":Population,"BRate":BRate}
# mydict
# list1=[Country,Population,BRate]
df3=pd.DataFrame(mydict)
df5=df3[["Country", "Population"]]
print(df5)
print("==============================================================")
print(df5.head(6))

  Country  Population
0     PAk          12
1     IND          34
2     USA          25
3     UAE          45
4   PARAS          67
5  EUROPE          89
6  FRANCE          90
7  RUSSIA          12
8  SAUDIA          34
==============================================================
  Country  Population
0     PAk          12
1     IND          34
2     USA          25
3     UAE          45
4   PARAS          67
5  EUROPE          89

In [ ]:
import numpy as np
list1=[Country,Population,BRate]
df4=pd.DataFrame(list1)
# df5=pd.DataFrame(np.transpose(list1))
print(df4)
# print(df5)

     0    1    2    3      4       5       6       7       8
0  PAk  IND  USA  UAE  PARAS  EUROPE  FRANCE  RUSSIA  SAUDIA
1   12   34   25   45     67      89      90      12      34
2  345  567  234  678    890    2345     567     896    5678

In [ ]:
#Creating a dataframe using dictionary
Country=["PAk","IND","USA","UAE","PARAS","EUROPE","FRANCE","RUSSIA","SAUDIA"]
Population=[12,34,25,45,67,89,90,12,34]
BRate=[345,567,234,678,890,2345,567,896,5678]
mydict={"Country":Country,"Population":Population,"BRate":BRate}
df5=pd.DataFrame(mydict, index=['row_1','row_2','row_1','row_2','row_1','row_2','row_1','row_2','row_1'])
df5

      Country  Population  BRate
row_1     PAk          12    345
row_2     IND          34    567
row_1     USA          25    234
row_2     UAE          45    678
row_1   PARAS          67    890
row_2  EUROPE          89   2345
row_1  FRANCE          90    567
row_2  RUSSIA          12    896
row_1  SAUDIA          34   5678

In [ ]:
#creating label for large dataset
row_labels=[f"row_{i}" for i in range(1,10)]
df6=pd.DataFrame(mydict, row_labels)
print(df6)

      Country  Population  BRate
row_1     PAk          12    345
row_2     IND          34    567
row_3     USA          25    234
row_4     UAE          45    678
row_5   PARAS          67    890
row_6  EUROPE          89   2345
row_7  FRANCE          90    567
row_8  RUSSIA          12    896
row_9  SAUDIA          34   5678

# **Dealing with Rows and Columns in Pandas DataFrame**

In [ ]:
#extracting two columns
df7=df6[['Country', 'Population']]
df7

      Country  Population
row_1     PAk          12
row_2     IND          34
row_3     USA          25
row_4     UAE          45
row_5   PARAS          67
row_6  EUROPE          89
row_7  FRANCE          90
row_8  RUSSIA          12
row_9  SAUDIA          34

In [ ]:
#droping column()
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
row_label=[f"label_{i}" for i in range(1,5)]
myframe=pd.DataFrame(data,row_label)
print(myframe)

           Name  Age    Address Qualification
label_1     Jai   27      Delhi           Msc
label_2  Princi   24     Kanpur            MA
label_3  Gaurav   22  Allahabad           MCA
label_4    Anuj   32    Kannauj           Phd

**Droping column**

Axis refer to axis along which operation will perform

We use axis=0 for row

We use axis=1 for column

In [ ]:
df6=myframe.drop(['Name','Age'],axis=1, inplace=True)
print(myframe)

print("----------------------------------------")

print(df6)

           Address Qualification
label_1      Delhi           Msc
label_2     Kanpur            MA
label_3  Allahabad           MCA
label_4    Kannauj           Phd
----------------------------------------
None

In [ ]:
#Adding new column
myframe['Score'] = [85, 90, 88, 95]

# Print the updated DataFrame
print("\nUpdated DataFrame with New Column:")
print(myframe)

Updated DataFrame with New Column:
           Address Qualification  Score
label_1      Delhi           Msc     85
label_2     Kanpur            MA     90
label_3  Allahabad           MCA     88
label_4    Kannauj           Phd     95

In [ ]:
myframe = myframe.assign(
    Score=[85, 90, 88, 55],
    Department=['IT', 'HR', 'Finance', 'Marketing']
)

# Print the updated DataFrame
print("\nUpdated DataFrame with Multiple New Columns:")
print(myframe)

Updated DataFrame with Multiple New Columns:
           Address Qualification  Score Department
label_1      Delhi           Msc     85         IT
label_2     Kanpur            MA     90         HR
label_3  Allahabad           MCA     88    Finance
label_4    Kannauj           Phd     55  Marketing

# **How to retrieve a row?**
Pandas provide a unique method to retrieve rows from a Data frame. DataFrame.loc[] method is a method that takes only index labels and returns row or dataframe

In [ ]:
#row selection
newdata = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18],
           "Grades":["a","b","c","d"]
        }
# frame1=pd.DataFrame(newdata)
labels=[f"Row_{i}" for i in range(1,5)]
frame1=pd.DataFrame(newdata,labels)
print("original dataset")
print(frame1)
print("----------------------------------------")
print("Dataset after applying loc method")
fr1=frame1.loc[['Row_1','Row_2']]
print(fr1)

original dataset
        Name  Age Grades
Row_1    Tom   20      a
Row_2   nick   21      b
Row_3  krish   19      c
Row_4   jack   18      d
----------------------------------------
Dataset after applying loc method
       Name  Age Grades
Row_1   Tom   20      a
Row_2  nick   21      b

In [ ]:
#iloc retrieve row based on postion or index
newdata = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18],
           "Grades":["a","b","c","d"]
        }
labels=[f"Row_{i}" for i in range(1,5)]
frame1=pd.DataFrame(newdata,labels)
fr1=frame1.iloc[[1,2]]
print(fr1)

        Name  Age Grades
Row_2   nick   21      b
Row_3  krish   19      c

In [ ]:
#drop a row
newframe = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18],
           "Grades":["a","b","c","d"]
        }
labels1=[f"Row_{i}" for i in range(1,5)]
frame2=pd.DataFrame(newframe,labels1)
frame3=frame2.drop(["Row_1","Row_2"], axis=0, inplace=True)
print("Original DataFrame")
print(frame2)

print("DataFrame after inplace=False")
print(frame3)

Original DataFrame
        Name  Age Grades
Row_3  krish   19      c
Row_4   jack   18      d
DataFrame after inplace=False
None

In [ ]:
#Add a row
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva','xyz'],
    'Age': [25, 30, 35, 40, 45,50],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer', 'Teacher','rtyuio'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix','sdfghjk'],
    'Salary': [70000, 80000, 60000, 90000, 75000,3456789]
}
row_labels=[f"ROW_{i}" for i in range(1,7)]
myframes=pd.DataFrame(data_dict, row_labels)
print(myframes)
myframes.loc["Row_2"]=['ali',100,'animal','USA',7890]
print(myframes)

          Name  Age Occupation         City   Salary
ROW_1    Alice   25   Engineer     New York    70000
ROW_2      Bob   30     Doctor  Los Angeles    80000
ROW_3  Charlie   35     Artist      Chicago    60000
ROW_4    David   40     Lawyer      Houston    90000
ROW_5      Eva   45    Teacher      Phoenix    75000
ROW_6      xyz   50     rtyuio      sdfghjk  3456789
          Name  Age Occupation         City   Salary
ROW_1    Alice   25   Engineer     New York    70000
ROW_2      Bob   30     Doctor  Los Angeles    80000
ROW_3  Charlie   35     Artist      Chicago    60000
ROW_4    David   40     Lawyer      Houston    90000
ROW_5      Eva   45    Teacher      Phoenix    75000
ROW_6      xyz   50     rtyuio      sdfghjk  3456789
Row_2      ali  100     animal          USA     7890

In [ ]:
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva','xyz'],
    'Age': [25, 30, 35, 40, 45,50],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer', 'Teacher','rtyuio'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix','sdfghjk'],
    'Salary': [70000, 80000, 60000, 90000, 75000,3456789]
}
labels=[f"Label_{i}" for i in range(1,7)]
df8=pd.DataFrame(data_dict,labels)
print(df8)

            Name  Age Occupation         City   Salary
Label_1    Alice   25   Engineer     New York    70000
Label_2      Bob   30     Doctor  Los Angeles    80000
Label_3  Charlie   35     Artist      Chicago    60000
Label_4    David   40     Lawyer      Houston    90000
Label_5      Eva   45    Teacher      Phoenix    75000
Label_6      xyz   50     rtyuio      sdfghjk  3456789

In [ ]:
new_row=pd.DataFrame([['David',   '40',     'Lawyer'     , 'Houston'    ,'90000']], columns=['Name','Age','Occupation','City','Salary'])
# print(new_row)
df9=pd.concat([df8.iloc[:2], new_row, df8.iloc[2:]], ignore_index=True)
print(df9)

      Name Age Occupation         City   Salary
0    Alice  25   Engineer     New York    70000
1      Bob  30     Doctor  Los Angeles    80000
2    David  40     Lawyer      Houston    90000
3  Charlie  35     Artist      Chicago    60000
4    David  40     Lawyer      Houston    90000
5      Eva  45    Teacher      Phoenix    75000
6      xyz  50     rtyuio      sdfghjk  3456789

In [ ]:

df_no_duplicates = df9.drop_duplicates(subset=['Name'])
print(df_no_duplicates)

      Name Age Occupation         City   Salary
0    Alice  25   Engineer     New York    70000
1      Bob  30     Doctor  Los Angeles    80000
2    David  40     Lawyer      Houston    90000
3  Charlie  35     Artist      Chicago    60000
5      Eva  45    Teacher      Phoenix    75000
6      xyz  50     rtyuio      sdfghjk  3456789

In [ ]:
#remove duplicates
df_no_duplicates = df9.drop_duplicates(subset=['Name'],keep=False) #first, alst, false
print(df_no_duplicates)

      Name Age Occupation         City   Salary
0    Alice  25   Engineer     New York    70000
1      Bob  30     Doctor  Los Angeles    80000
3  Charlie  35     Artist      Chicago    60000
5      Eva  45    Teacher      Phoenix    75000
6      xyz  50     rtyuio      sdfghjk  3456789

In [ ]:
import pandas as pd
# Original data dictionary with 5 rows
data_dict1 = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer', 'Teacher'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 60000, 90000, 75000]
}

# Create the DataFrame from the dictionary
df = pd.DataFrame(data_dict1)

# Function to take input for new rows
def add_new_row():
    name = input("Enter Name: ")
    age = int(input("Enter Age: "))
    occupation = input("Enter Occupation: ")
    city = input("Enter City: ")
    salary = int(input("Enter Salary: "))

    return {'Name': name, 'Age': age, 'Occupation': occupation, 'City': city, 'Salary': salary} #returning a dictionary

# Create a list to store new rows
new_rows = []

# Loop to add multiple rows (ask user for each)
num_rows = int(input("How many rows would you like to add? "))
for i in range(num_rows):
    print(f"\nEnter details for row {i+1}:")
    new_row = add_new_row()
    print(new_row)
    new_rows.append(new_row)
    print(new_rows)

# Convert the list of new rows to a DataFrame
new_rows_df = pd.DataFrame(new_rows)
print(new_rows_df)
# Concatenate the original DataFrame with the new rows
df = pd.concat([df.iloc[:2], new_rows_df, df.iloc[2:]], ignore_index=True)

# Print the updated DataFrame
print("\nUpdated DataFrame:")
print(df)

In [ ]:
|